name: face_recognition
description: This is the Face Recognition Flutter app which can be running on both Android & iOS platform.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <=3.2.3"
  flutter: ">=1.10.0"

dependencies:
  camera: ^0.10.5+5
  cupertino_icons: ^1.0.6
  google_ml_vision: ^0.0.8
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  image: ^4.1.3
  tflite_flutter: ^0.10.4
  path_provider: ^2.1.1
  bitmap: ^0.1.3

flutter:
  uses-material-design: true

  assets:
    - assets/
